### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by batjko** [successkrisz/effect-lambda#1]
Would be great to have some guidelines how best to contribute to this project.
Any conventions to keep in mind, any rules to follow, any gotchas to watch out for?

**Comment by successkrisz** [comment]
Thanks for the input, added a contribution guide 👍 - https://github.com/successkrisz/effect-lambda/commit/ca15d510bce25b988fe71ae5e11fc02f95198bb1
